// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.main.myprojectspa.domain.projectspa;

import com.main.myprojectspa.domain.projectspa.CustomerType;
import com.main.myprojectspa.domain.projectspa.CustomerTypeDataOnDemand;
import com.main.myprojectspa.domain.projectspa.CustomerTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CustomerTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CustomerTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CustomerTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CustomerTypeIntegrationTest: @Transactional;
    
    @Autowired
    CustomerTypeDataOnDemand CustomerTypeIntegrationTest.dod;
    
    @Test
    public void CustomerTypeIntegrationTest.testCountCustomerTypes() {
        Assert.assertNotNull("Data on demand for 'CustomerType' failed to initialize correctly", dod.getRandomCustomerType());
        long count = CustomerType.countCustomerTypes();
        Assert.assertTrue("Counter for 'CustomerType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CustomerTypeIntegrationTest.testFindCustomerType() {
        CustomerType obj = dod.getRandomCustomerType();
        Assert.assertNotNull("Data on demand for 'CustomerType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CustomerType' failed to provide an identifier", id);
        obj = CustomerType.findCustomerType(id);
        Assert.assertNotNull("Find method for 'CustomerType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CustomerType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CustomerTypeIntegrationTest.testFindAllCustomerTypes() {
        Assert.assertNotNull("Data on demand for 'CustomerType' failed to initialize correctly", dod.getRandomCustomerType());
        long count = CustomerType.countCustomerTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'CustomerType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CustomerType> result = CustomerType.findAllCustomerTypes();
        Assert.assertNotNull("Find all method for 'CustomerType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CustomerType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CustomerTypeIntegrationTest.testFindCustomerTypeEntries() {
        Assert.assertNotNull("Data on demand for 'CustomerType' failed to initialize correctly", dod.getRandomCustomerType());
        long count = CustomerType.countCustomerTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CustomerType> result = CustomerType.findCustomerTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CustomerType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CustomerType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CustomerTypeIntegrationTest.testFlush() {
        CustomerType obj = dod.getRandomCustomerType();
        Assert.assertNotNull("Data on demand for 'CustomerType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CustomerType' failed to provide an identifier", id);
        obj = CustomerType.findCustomerType(id);
        Assert.assertNotNull("Find method for 'CustomerType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCustomerType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'CustomerType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CustomerTypeIntegrationTest.testMergeUpdate() {
        CustomerType obj = dod.getRandomCustomerType();
        Assert.assertNotNull("Data on demand for 'CustomerType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CustomerType' failed to provide an identifier", id);
        obj = CustomerType.findCustomerType(id);
        boolean modified =  dod.modifyCustomerType(obj);
        Integer currentVersion = obj.getVersion();
        CustomerType merged = (CustomerType)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CustomerType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CustomerTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'CustomerType' failed to initialize correctly", dod.getRandomCustomerType());
        CustomerType obj = dod.getNewTransientCustomerType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CustomerType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CustomerType' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'CustomerType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CustomerTypeIntegrationTest.testRemove() {
        CustomerType obj = dod.getRandomCustomerType();
        Assert.assertNotNull("Data on demand for 'CustomerType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CustomerType' failed to provide an identifier", id);
        obj = CustomerType.findCustomerType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'CustomerType' with identifier '" + id + "'", CustomerType.findCustomerType(id));
    }
    
}
