// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.main.myprojectspa.domain.projectspa;

import com.main.myprojectspa.domain.projectspa.CustomerType;
import com.main.myprojectspa.domain.projectspa.CustomerTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect CustomerTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CustomerTypeDataOnDemand: @Component;
    
    private Random CustomerTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<CustomerType> CustomerTypeDataOnDemand.data;
    
    public CustomerType CustomerTypeDataOnDemand.getNewTransientCustomerType(int index) {
        CustomerType obj = new CustomerType();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setCustomerPrivillege(obj, index);
        setCustomerTypeCode(obj, index);
        setCustomerTypeName(obj, index);
        setStatus(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void CustomerTypeDataOnDemand.setCreatedBy(CustomerType obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void CustomerTypeDataOnDemand.setCreatedDate(CustomerType obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void CustomerTypeDataOnDemand.setCustomerPrivillege(CustomerType obj, int index) {
        String customerPrivillege = "customerPrivillege_" + index;
        obj.setCustomerPrivillege(customerPrivillege);
    }
    
    public void CustomerTypeDataOnDemand.setCustomerTypeCode(CustomerType obj, int index) {
        Integer customerTypeCode = new Integer(index);
        obj.setCustomerTypeCode(customerTypeCode);
    }
    
    public void CustomerTypeDataOnDemand.setCustomerTypeName(CustomerType obj, int index) {
        String customerTypeName = "customerTypeName_" + index;
        obj.setCustomerTypeName(customerTypeName);
    }
    
    public void CustomerTypeDataOnDemand.setStatus(CustomerType obj, int index) {
        String status = "status_" + index;
        obj.setStatus(status);
    }
    
    public void CustomerTypeDataOnDemand.setUpdatedBy(CustomerType obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void CustomerTypeDataOnDemand.setUpdatedDate(CustomerType obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public CustomerType CustomerTypeDataOnDemand.getSpecificCustomerType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CustomerType obj = data.get(index);
        Long id = obj.getId();
        return CustomerType.findCustomerType(id);
    }
    
    public CustomerType CustomerTypeDataOnDemand.getRandomCustomerType() {
        init();
        CustomerType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return CustomerType.findCustomerType(id);
    }
    
    public boolean CustomerTypeDataOnDemand.modifyCustomerType(CustomerType obj) {
        return false;
    }
    
    public void CustomerTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = CustomerType.findCustomerTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CustomerType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CustomerType>();
        for (int i = 0; i < 10; i++) {
            CustomerType obj = getNewTransientCustomerType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
