// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.main.myprojectspa.domain.projectspa;

import com.main.myprojectspa.domain.projectspa.Information;
import com.main.myprojectspa.domain.projectspa.InformationDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect InformationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InformationDataOnDemand: @Component;
    
    private Random InformationDataOnDemand.rnd = new SecureRandom();
    
    private List<Information> InformationDataOnDemand.data;
    
    public Information InformationDataOnDemand.getNewTransientInformation(int index) {
        Information obj = new Information();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setInformationDetail(obj, index);
        setInformationName(obj, index);
        setInformationPictureName(obj, index);
        setStatus(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void InformationDataOnDemand.setCreatedBy(Information obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void InformationDataOnDemand.setCreatedDate(Information obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void InformationDataOnDemand.setInformationDetail(Information obj, int index) {
        String informationDetail = "informationDetail_" + index;
        obj.setInformationDetail(informationDetail);
    }
    
    public void InformationDataOnDemand.setInformationName(Information obj, int index) {
        String informationName = "informationName_" + index;
        obj.setInformationName(informationName);
    }
    
    public void InformationDataOnDemand.setInformationPictureName(Information obj, int index) {
        String informationPictureName = "informationPictureName_" + index;
        obj.setInformationPictureName(informationPictureName);
    }
    
    public void InformationDataOnDemand.setStatus(Information obj, int index) {
        String status = "status_" + index;
        obj.setStatus(status);
    }
    
    public void InformationDataOnDemand.setUpdatedBy(Information obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void InformationDataOnDemand.setUpdatedDate(Information obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public Information InformationDataOnDemand.getSpecificInformation(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Information obj = data.get(index);
        Long id = obj.getId();
        return Information.findInformation(id);
    }
    
    public Information InformationDataOnDemand.getRandomInformation() {
        init();
        Information obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Information.findInformation(id);
    }
    
    public boolean InformationDataOnDemand.modifyInformation(Information obj) {
        return false;
    }
    
    public void InformationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Information.findInformationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Information' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Information>();
        for (int i = 0; i < 10; i++) {
            Information obj = getNewTransientInformation(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
