// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.main.myprojectspa.domain.projectspa;

import com.main.myprojectspa.domain.projectspa.MassageTypes;
import com.main.myprojectspa.domain.projectspa.MassageTypesDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect MassageTypesDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MassageTypesDataOnDemand: @Component;
    
    private Random MassageTypesDataOnDemand.rnd = new SecureRandom();
    
    private List<MassageTypes> MassageTypesDataOnDemand.data;
    
    public MassageTypes MassageTypesDataOnDemand.getNewTransientMassageTypes(int index) {
        MassageTypes obj = new MassageTypes();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setMassageTypeCode(obj, index);
        setMassageTypeName(obj, index);
        setStatus(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void MassageTypesDataOnDemand.setCreatedBy(MassageTypes obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void MassageTypesDataOnDemand.setCreatedDate(MassageTypes obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void MassageTypesDataOnDemand.setMassageTypeCode(MassageTypes obj, int index) {
        String massageTypeCode = "massageTypeCode_" + index;
        obj.setMassageTypeCode(massageTypeCode);
    }
    
    public void MassageTypesDataOnDemand.setMassageTypeName(MassageTypes obj, int index) {
        String massageTypeName = "massageTypeName_" + index;
        obj.setMassageTypeName(massageTypeName);
    }
    
    public void MassageTypesDataOnDemand.setStatus(MassageTypes obj, int index) {
        String status = "status_" + index;
        obj.setStatus(status);
    }
    
    public void MassageTypesDataOnDemand.setUpdatedBy(MassageTypes obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void MassageTypesDataOnDemand.setUpdatedDate(MassageTypes obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public MassageTypes MassageTypesDataOnDemand.getSpecificMassageTypes(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MassageTypes obj = data.get(index);
        Long id = obj.getId();
        return MassageTypes.findMassageTypes(id);
    }
    
    public MassageTypes MassageTypesDataOnDemand.getRandomMassageTypes() {
        init();
        MassageTypes obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return MassageTypes.findMassageTypes(id);
    }
    
    public boolean MassageTypesDataOnDemand.modifyMassageTypes(MassageTypes obj) {
        return false;
    }
    
    public void MassageTypesDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = MassageTypes.findMassageTypesEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MassageTypes' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MassageTypes>();
        for (int i = 0; i < 10; i++) {
            MassageTypes obj = getNewTransientMassageTypes(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
