// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.main.myprojectspa.domain.projectspa;

import com.main.myprojectspa.domain.projectspa.CustomerDataOnDemand;
import com.main.myprojectspa.domain.projectspa.EmployeeDataOnDemand;
import com.main.myprojectspa.domain.projectspa.MassageDataOnDemand;
import com.main.myprojectspa.domain.projectspa.MassageEvent;
import com.main.myprojectspa.domain.projectspa.MassageEventDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MassageEventDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MassageEventDataOnDemand: @Component;
    
    private Random MassageEventDataOnDemand.rnd = new SecureRandom();
    
    private List<MassageEvent> MassageEventDataOnDemand.data;
    
    @Autowired
    EmployeeDataOnDemand MassageEventDataOnDemand.employeeDataOnDemand;
    
    @Autowired
    MassageDataOnDemand MassageEventDataOnDemand.massageDataOnDemand;
    
    @Autowired
    CustomerDataOnDemand MassageEventDataOnDemand.customerDataOnDemand;
    
    public MassageEvent MassageEventDataOnDemand.getNewTransientMassageEvent(int index) {
        MassageEvent obj = new MassageEvent();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setEventEndTime(obj, index);
        setEventStartTime(obj, index);
        setReserveDate(obj, index);
        setStatus(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void MassageEventDataOnDemand.setCreatedBy(MassageEvent obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void MassageEventDataOnDemand.setCreatedDate(MassageEvent obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void MassageEventDataOnDemand.setEventEndTime(MassageEvent obj, int index) {
        Date eventEndTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setEventEndTime(eventEndTime);
    }
    
    public void MassageEventDataOnDemand.setEventStartTime(MassageEvent obj, int index) {
        Date eventStartTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setEventStartTime(eventStartTime);
    }
    
    public void MassageEventDataOnDemand.setReserveDate(MassageEvent obj, int index) {
        Date reserveDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setReserveDate(reserveDate);
    }
    
    public void MassageEventDataOnDemand.setStatus(MassageEvent obj, int index) {
        String status = "status_" + index;
        obj.setStatus(status);
    }
    
    public void MassageEventDataOnDemand.setUpdatedBy(MassageEvent obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void MassageEventDataOnDemand.setUpdatedDate(MassageEvent obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public MassageEvent MassageEventDataOnDemand.getSpecificMassageEvent(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MassageEvent obj = data.get(index);
        Long id = obj.getId();
        return MassageEvent.findMassageEvent(id);
    }
    
    public MassageEvent MassageEventDataOnDemand.getRandomMassageEvent() {
        init();
        MassageEvent obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return MassageEvent.findMassageEvent(id);
    }
    
    public boolean MassageEventDataOnDemand.modifyMassageEvent(MassageEvent obj) {
        return false;
    }
    
    public void MassageEventDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = MassageEvent.findMassageEventEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MassageEvent' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MassageEvent>();
        for (int i = 0; i < 10; i++) {
            MassageEvent obj = getNewTransientMassageEvent(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
