// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.main.myprojectspa.domain.projectspa;

import com.main.myprojectspa.domain.projectspa.ProductTypes;
import com.main.myprojectspa.domain.projectspa.ProductTypesDataOnDemand;
import com.main.myprojectspa.domain.projectspa.ProductTypesIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductTypesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductTypesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductTypesIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductTypesIntegrationTest: @Transactional;
    
    @Autowired
    ProductTypesDataOnDemand ProductTypesIntegrationTest.dod;
    
    @Test
    public void ProductTypesIntegrationTest.testCountProductTypeses() {
        Assert.assertNotNull("Data on demand for 'ProductTypes' failed to initialize correctly", dod.getRandomProductTypes());
        long count = ProductTypes.countProductTypeses();
        Assert.assertTrue("Counter for 'ProductTypes' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductTypesIntegrationTest.testFindProductTypes() {
        ProductTypes obj = dod.getRandomProductTypes();
        Assert.assertNotNull("Data on demand for 'ProductTypes' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductTypes' failed to provide an identifier", id);
        obj = ProductTypes.findProductTypes(id);
        Assert.assertNotNull("Find method for 'ProductTypes' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProductTypes' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductTypesIntegrationTest.testFindAllProductTypeses() {
        Assert.assertNotNull("Data on demand for 'ProductTypes' failed to initialize correctly", dod.getRandomProductTypes());
        long count = ProductTypes.countProductTypeses();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProductTypes', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProductTypes> result = ProductTypes.findAllProductTypeses();
        Assert.assertNotNull("Find all method for 'ProductTypes' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProductTypes' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductTypesIntegrationTest.testFindProductTypesEntries() {
        Assert.assertNotNull("Data on demand for 'ProductTypes' failed to initialize correctly", dod.getRandomProductTypes());
        long count = ProductTypes.countProductTypeses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProductTypes> result = ProductTypes.findProductTypesEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ProductTypes' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProductTypes' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductTypesIntegrationTest.testFlush() {
        ProductTypes obj = dod.getRandomProductTypes();
        Assert.assertNotNull("Data on demand for 'ProductTypes' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductTypes' failed to provide an identifier", id);
        obj = ProductTypes.findProductTypes(id);
        Assert.assertNotNull("Find method for 'ProductTypes' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProductTypes(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ProductTypes' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductTypesIntegrationTest.testMergeUpdate() {
        ProductTypes obj = dod.getRandomProductTypes();
        Assert.assertNotNull("Data on demand for 'ProductTypes' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductTypes' failed to provide an identifier", id);
        obj = ProductTypes.findProductTypes(id);
        boolean modified =  dod.modifyProductTypes(obj);
        Integer currentVersion = obj.getVersion();
        ProductTypes merged = (ProductTypes)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ProductTypes' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductTypesIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ProductTypes' failed to initialize correctly", dod.getRandomProductTypes());
        ProductTypes obj = dod.getNewTransientProductTypes(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProductTypes' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ProductTypes' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ProductTypes' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductTypesIntegrationTest.testRemove() {
        ProductTypes obj = dod.getRandomProductTypes();
        Assert.assertNotNull("Data on demand for 'ProductTypes' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductTypes' failed to provide an identifier", id);
        obj = ProductTypes.findProductTypes(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ProductTypes' with identifier '" + id + "'", ProductTypes.findProductTypes(id));
    }
    
}
