// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.main.myprojectspa.domain.projectspa;

import com.main.myprojectspa.domain.projectspa.ProductTypesIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ProductTypesIntegrationTest_Roo_Configurable {
    
    declare @type: ProductTypesIntegrationTest: @Configurable;
    
}
