// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.main.myprojectspa.domain.projectspa;

import com.main.myprojectspa.domain.projectspa.ShoppingEvent;
import com.main.myprojectspa.domain.projectspa.ShoppingEventDataOnDemand;
import com.main.myprojectspa.domain.projectspa.ShoppingEventIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ShoppingEventIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ShoppingEventIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ShoppingEventIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ShoppingEventIntegrationTest: @Transactional;
    
    @Autowired
    ShoppingEventDataOnDemand ShoppingEventIntegrationTest.dod;
    
    @Test
    public void ShoppingEventIntegrationTest.testCountShoppingEvents() {
        Assert.assertNotNull("Data on demand for 'ShoppingEvent' failed to initialize correctly", dod.getRandomShoppingEvent());
        long count = ShoppingEvent.countShoppingEvents();
        Assert.assertTrue("Counter for 'ShoppingEvent' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ShoppingEventIntegrationTest.testFindShoppingEvent() {
        ShoppingEvent obj = dod.getRandomShoppingEvent();
        Assert.assertNotNull("Data on demand for 'ShoppingEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ShoppingEvent' failed to provide an identifier", id);
        obj = ShoppingEvent.findShoppingEvent(id);
        Assert.assertNotNull("Find method for 'ShoppingEvent' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ShoppingEvent' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ShoppingEventIntegrationTest.testFindAllShoppingEvents() {
        Assert.assertNotNull("Data on demand for 'ShoppingEvent' failed to initialize correctly", dod.getRandomShoppingEvent());
        long count = ShoppingEvent.countShoppingEvents();
        Assert.assertTrue("Too expensive to perform a find all test for 'ShoppingEvent', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ShoppingEvent> result = ShoppingEvent.findAllShoppingEvents();
        Assert.assertNotNull("Find all method for 'ShoppingEvent' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ShoppingEvent' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ShoppingEventIntegrationTest.testFindShoppingEventEntries() {
        Assert.assertNotNull("Data on demand for 'ShoppingEvent' failed to initialize correctly", dod.getRandomShoppingEvent());
        long count = ShoppingEvent.countShoppingEvents();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ShoppingEvent> result = ShoppingEvent.findShoppingEventEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ShoppingEvent' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ShoppingEvent' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ShoppingEventIntegrationTest.testFlush() {
        ShoppingEvent obj = dod.getRandomShoppingEvent();
        Assert.assertNotNull("Data on demand for 'ShoppingEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ShoppingEvent' failed to provide an identifier", id);
        obj = ShoppingEvent.findShoppingEvent(id);
        Assert.assertNotNull("Find method for 'ShoppingEvent' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyShoppingEvent(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ShoppingEvent' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ShoppingEventIntegrationTest.testMergeUpdate() {
        ShoppingEvent obj = dod.getRandomShoppingEvent();
        Assert.assertNotNull("Data on demand for 'ShoppingEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ShoppingEvent' failed to provide an identifier", id);
        obj = ShoppingEvent.findShoppingEvent(id);
        boolean modified =  dod.modifyShoppingEvent(obj);
        Integer currentVersion = obj.getVersion();
        ShoppingEvent merged = (ShoppingEvent)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ShoppingEvent' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ShoppingEventIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ShoppingEvent' failed to initialize correctly", dod.getRandomShoppingEvent());
        ShoppingEvent obj = dod.getNewTransientShoppingEvent(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ShoppingEvent' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ShoppingEvent' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ShoppingEvent' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ShoppingEventIntegrationTest.testRemove() {
        ShoppingEvent obj = dod.getRandomShoppingEvent();
        Assert.assertNotNull("Data on demand for 'ShoppingEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ShoppingEvent' failed to provide an identifier", id);
        obj = ShoppingEvent.findShoppingEvent(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ShoppingEvent' with identifier '" + id + "'", ShoppingEvent.findShoppingEvent(id));
    }
    
}
