// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.main.myprojectspa.domain.projectspa;

import com.main.myprojectspa.domain.projectspa.CustomerDataOnDemand;
import com.main.myprojectspa.domain.projectspa.ProductDataOnDemand;
import com.main.myprojectspa.domain.projectspa.ShoppingEvent;
import com.main.myprojectspa.domain.projectspa.ShoppingEventDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ShoppingEventDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ShoppingEventDataOnDemand: @Component;
    
    private Random ShoppingEventDataOnDemand.rnd = new SecureRandom();
    
    private List<ShoppingEvent> ShoppingEventDataOnDemand.data;
    
    @Autowired
    CustomerDataOnDemand ShoppingEventDataOnDemand.customerDataOnDemand;
    
    @Autowired
    ProductDataOnDemand ShoppingEventDataOnDemand.productDataOnDemand;
    
    public ShoppingEvent ShoppingEventDataOnDemand.getNewTransientShoppingEvent(int index) {
        ShoppingEvent obj = new ShoppingEvent();
        setAllPrice(obj, index);
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setEventCreateDate(obj, index);
        setStatus(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void ShoppingEventDataOnDemand.setAllPrice(ShoppingEvent obj, int index) {
        Float allPrice = new Integer(index).floatValue();
        obj.setAllPrice(allPrice);
    }
    
    public void ShoppingEventDataOnDemand.setCreatedBy(ShoppingEvent obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void ShoppingEventDataOnDemand.setCreatedDate(ShoppingEvent obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void ShoppingEventDataOnDemand.setEventCreateDate(ShoppingEvent obj, int index) {
        Date eventCreateDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setEventCreateDate(eventCreateDate);
    }
    
    public void ShoppingEventDataOnDemand.setStatus(ShoppingEvent obj, int index) {
        String status = "status_" + index;
        obj.setStatus(status);
    }
    
    public void ShoppingEventDataOnDemand.setUpdatedBy(ShoppingEvent obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void ShoppingEventDataOnDemand.setUpdatedDate(ShoppingEvent obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public ShoppingEvent ShoppingEventDataOnDemand.getSpecificShoppingEvent(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ShoppingEvent obj = data.get(index);
        Long id = obj.getId();
        return ShoppingEvent.findShoppingEvent(id);
    }
    
    public ShoppingEvent ShoppingEventDataOnDemand.getRandomShoppingEvent() {
        init();
        ShoppingEvent obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ShoppingEvent.findShoppingEvent(id);
    }
    
    public boolean ShoppingEventDataOnDemand.modifyShoppingEvent(ShoppingEvent obj) {
        return false;
    }
    
    public void ShoppingEventDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ShoppingEvent.findShoppingEventEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ShoppingEvent' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ShoppingEvent>();
        for (int i = 0; i < 10; i++) {
            ShoppingEvent obj = getNewTransientShoppingEvent(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
